title: Hey! # your name (or website title) here
logo: "/images/itsame.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Alyssa Marie Dico Maravilla
  <br>
  I'm currently in grad school. And I make things.
  <br><br>
  <a href="/portfolio">Check out my work!</a>
  <br><br> 
  <a href="research">Research Projects</a>
  <br><br>
  <a href="https://www.linkedin.com/in/alyssam-maravilla/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="/resume">Current Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
